Add creativo/Inventos.md y Upd herramientasHeroes.md: -Stormbreaker
Jjonas777Code/herramientas-heroesEDU-demo pull request #1
Opened 2024-10-10 23:07 UTC by Jjonas777

### Modificaciones
- Elimine la herramienta Stormbreaker.

### Adiciones
- Agregue la carpeta y archivo creativo/Inventos.md
- Agregue contenido al archivo Inventos.md un esquema de creación de nuevos instrumentos para los héroes.

2024-10-10 23:46 UTC, Jjonas777Code requested changes
Revisión:
- Por favor no eliminar a Stormbreaker
- Adicional el nombre del nuevo archivo deben estar con minúsculas por estándar.

2024-10-10 23:46 UTC, Jjonas777Code commented on herramientasHeroes.md
> -5. Stormbreaker
@Jjonas777 No quiero que se elimine a Stormbreaker ya que es una herramienta importante.

2024-10-11 00:06 UTC, Jjonas777Code commented on herramientasHeroes.md
> -5. Stormbreaker
@Jjonas777Code Hola ok está bien se reestablecerá la herramienta Stormbreaker.

2024-10-11 00:08 UTC, Jjonas777 commented on herramientasHeroes.md
> -5. Stormbreaker
Hola @Jjonas777Code ok está bien se reestablecerá la herramienta Stormbreaker.

2024-10-11 03:47 UTC, Jjonas777Code approved these changes
Ok está correcto. Gracias por tu colaboración!!!

2024-10-11 04:08 UTC, merged